# Generated by Django 3.1.3 on 2020-11-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='user',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
