# Generated by Django 3.1.3 on 2020-11-10 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20201110_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='password',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
